'use client';

import { ArrowUpRight } from 'lucide-react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

const services = [
  { title: 'Brand & creative direction', description: 'Find the story, the look, and the voice that make your business recognizable. A clear direction for the website and the people it needs to reach.', tags: ['Brand strategy', 'Visual identity', 'Art direction'], href: '/work/sassanos-clovis-website-concept', link: 'See the Sassano’s design study' },
  { title: 'Website design & development', description: 'A considered first impression with practical work behind it. Responsive layouts, useful content, and a clear path from curious visitor to real conversation.', tags: ['Website design', 'Development', 'E-commerce'], href: '/work/las-mananitas-restaurant-website-concept', link: 'See the restaurant design study' },
  { title: 'Digital tools & automation', description: 'Focused interfaces and useful software for real tasks. Shape the workflow around the person doing the work, rather than asking them to adapt to unnecessary complexity.', tags: ['Product design', 'Custom software', 'Workflow automation'], href: '/work/jobwarden', link: 'Explore JobWarden' },
  { title: 'Website care & improvements', description: 'Keep the useful things working and improve the details that need attention. Agree a practical scope for updates, refinements, and technical guidance as your business changes.', tags: ['Website care', 'Ongoing improvements', 'Technical guidance'], href: '#contact', link: 'Discuss your website' },
];
export function Services() {
  return <section className="services-section shell" id="services" aria-labelledby="services-heading"><div className="services-intro" data-reveal><p className="section-label mono">02 / Thought through. Built right.</p><h2 id="services-heading">Good design.<br />Serious capability.</h2><p>Creative thinking and technical care, brought together around what your business actually needs.</p><a className="arrow-link" href="/services/web-design">How we can work together<ArrowUpRight size={18} aria-hidden="true" /></a></div><Accordion className="service-accordion" defaultValue={['service-1']} data-reveal>{services.map((service, index) => <AccordionItem value={`service-${index}`} key={service.title} className="service-item"><AccordionTrigger className="service-trigger"><span className="service-number mono">0{index + 1}</span><span>{service.title}</span></AccordionTrigger><AccordionContent className="service-content"><p>{service.description}</p><div className="service-tags">{service.tags.map(tag => <span key={tag}>{tag}</span>)}</div><a className="quiet-link service-proof" href={service.href}>{service.link}<ArrowUpRight size={16} aria-hidden="true" /></a></AccordionContent></AccordionItem>)}</Accordion></section>;
}
